### PR TITLE
Move to pyspf package

### PR DESCRIPTION
**Pull request by sloev**
Hi there

Your module is called *spf* exactly like this (very popular) package [SanicPluginsFrameworks](https://github.com/ashleysommer/sanicpluginsframework/blob/master/setup.py#L50) 

I want to be able to use both packages so i made this PR for you to consider, tests are green.

The pr moves all the code into the *./pyspf/* folder and i have changed the README and test to use this as well.

I have also added the dependencies into the setup.py so its easier to install.
(i specified individual versions of pydns according to python 2 or 3)

I hope you will consider merging this so i can use both libraries at the same time in the future!

Thanks for a great project!
kind regards - Johannes Valbjørn aka Sloev
:-)

### CODE REVIEW

**Comment by kitterma** [comment]
This project has been using the spf module name since 2004.  I think it would be ridiculous for us to rename because of a less than three year old project that obviously failed to evaluate the name space before using it.  There are many applications that use pyspf as it is and this would cause a lot of breakage.

Are you willing to find and provide updates for every application that uses pyspf?

**Comment by sloev** [comment]
Well if you have been developing this package since 2004 why is it then in this semi-unfinished non-conventional state?

I think your tone in the reply is off the charts and you should reconsider using words like `ridiculous` etc.

I am not affiliated to the *Sanic* project, i am just a user that wants to use *both packages* at once which you fail to let happen.

I will instead fork this package and publish it to pypi under a different name so people (that obey to conventions like packages etc) can still use your package.

By the way, here is some numbers for usage (as you can see: you're not the most popular kid in class):

*https://pypistats.org/packages/pyspf*
```
Downloads last day: 512
Downloads last week: 2,399
Downloads last month: 8,653
```
*https://pypistats.org/packages/sanic-plugins-framework*
```
Downloads last day: 1,411
Downloads last week: 7,014
Downloads last month: 24,904
```

so long and kind regards
Johannes

**Comment by kitterma** [comment]
Did you ask the other package to rename?  Typically in the case of a namespace conflict, it's the newer project that renames.  The structure of the package reflects it's age.

I agree it should be moved to setuptools, provide package requirements, and support more modern packaging approaches.  We've recently been discussing it in #19 .  I'm not the primary maintainer for the project.

If you're going to fork and rename something, I don't see why it should be us.

**Comment by sloev** [comment]
i will ask the other guys and refer to this discussion 👍 

hope you have a good one if i don't come back :-)

kind regards
johannes

**Comment by sloev** [comment]
Please find a reply from the other project here:
https://github.com/ashleysommer/sanicpluginsframework/issues/16#issuecomment-574408265
It sounds like they will rename in next major version.

Kind regards

**Comment by kitterma** [comment]
Thank you for working to resolve this and letting us know.  FTR, I'm not the project owner, just one of the developers on the project.  Based on that plan, I'm going to close this PR.

**Comment by sloev** [comment]
@kitterma hi, just wanted to share that sanic plugin framework has changed package name going forward so the issue is resolved :-)
https://github.com/ashleysommer/sanic-plugin-toolkit/issues/16#issuecomment-803595099

**Pull request closed without merging**
